/* ===========================================================================
   Concert Tracker -- app logic
   Reads window.CONCERT_DATA (generated by build-data.ps1) and renders every
   view client-side. No frameworks, no network. Charts are hand-rolled SVG.
   =========================================================================== */
(function () {
  "use strict";

  var RAW  = (window.CONCERT_DATA || []);
  var META = (window.CONCERT_META || {});

  var MONTHS = ["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"];
  var MONTHS_LONG = ["January","February","March","April","May","June","July",
                     "August","September","October","November","December"];

  // ----------------------------------------------------------------- helpers
  function esc(s) {
    return String(s == null ? "" : s)
      .replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;")
      .replace(/"/g, "&quot;");
  }
  function el(id) { return document.getElementById(id); }
  function ordinal(n) {
    var s = ["th","st","nd","rd"], v = n % 100;
    return n + (s[(v - 20) % 10] || s[v] || s[0]);
  }
  // parse "YYYY-MM-DD" without timezone shifts
  function parts(dstr) {
    if (!dstr) return null;
    var p = dstr.split("-");
    return { y: +p[0], m: +p[1], d: +p[2] };
  }
  function prettyDate(dstr) {
    var p = parts(dstr);
    if (!p) return "date unknown";
    return MONTHS_LONG[p.m - 1] + " " + p.d + ", " + p.y;
  }

  // Venue display map (config.js): raw spreadsheet text -> { name, aka[] }.
  // Display uses the current name; former/aka names surface only on the venue page.
  var VENUE_MAP = {};
  (function () {
    var src = (window.CONCERT_CONFIG && window.CONCERT_CONFIG.venueNames) || {};
    for (var k in src) { if (src.hasOwnProperty(k)) VENUE_MAP[k.toLowerCase()] = src[k]; }
  })();
  function resolveVenue(raw) {
    raw = String(raw || "").trim();
    var e = VENUE_MAP[raw.toLowerCase()];
    if (e) return { name: e.name || raw, aka: e.aka || [] };
    return { name: raw, aka: [] };
  }

  // Manual setlist.fm overrides (config.js): "artist|date" -> url. Wins over the
  // auto-resolved link (e.g. festival days where the API can't pick the right one).
  var SETLIST_OVERRIDES = {};
  (function () {
    var src = (window.CONCERT_CONFIG && window.CONCERT_CONFIG.setlistOverrides) || {};
    for (var k in src) { if (src.hasOwnProperty(k)) SETLIST_OVERRIDES[k.toLowerCase()] = src[k]; }
  })();
  function setlistOverrideFor(headliner, date) {
    if (!date) return null;
    return SETLIST_OVERRIDES[(String(headliner || "") + "|" + date).toLowerCase()] || null;
  }

  // ------------------------------------------------------------- data prep
  var SHOWS = RAW.map(function (s, i) {
    var p = parts(s.date);
    var pv = resolveVenue(s.venue);
    return {
      id: i,
      headliner: s.headliner || "",
      bands: (s.bands && s.bands.length ? s.bands : [s.headliner]).filter(Boolean),
      date: s.date || null,
      year: s.year || (p ? p.y : null),
      month: p ? p.m : null,
      day: p ? p.d : null,
      venue: pv.name,            // current display name (used everywhere)
      venueAka: pv.aka,          // former / other names (shown on the venue page)
      venueRaw: s.venue || "",   // original spreadsheet text (kept for search)
      city: s.city || "",
      state: s.state || "",
      // manual override wins; else the build-time resolved link; else search fallback
      setlistUrl: setlistOverrideFor(s.headliner, s.date) || s.setlistUrl || null,
      songs: s.songs || [],
      tourName: s.tourName || ""
    };
  });

  // chronological list of dated shows (asc), with lifetime ordinal
  var DATED = SHOWS.filter(function (s) { return s.date; })
                   .sort(function (a, b) { return a.date < b.date ? -1 : a.date > b.date ? 1 : a.id - b.id; });
  DATED.forEach(function (s, i) { s.ordinal = i + 1; });

  // Logical grouping: a band name -> the artist it counts under (from config.js).
  // Display always uses the original name; only counting/aggregation uses the group.
  // (case-insensitive, matching the spreadsheet however it's typed)
  var GROUPS = {};
  (function () {
    var src = (window.CONCERT_CONFIG && window.CONCERT_CONFIG.artistAliases) || {};
    for (var k in src) { if (src.hasOwnProperty(k)) GROUPS[k.toLowerCase()] = src[k]; }
  })();
  function groupOf(name) { return GROUPS[String(name || "").toLowerCase()] || name; }

  var ARTIST_BANNERS = {};
  (function () {
    var src = (window.CONCERT_CONFIG && window.CONCERT_CONFIG.artistBanners) || {};
    for (var k in src) { if (src.hasOwnProperty(k)) ARTIST_BANNERS[k.toLowerCase()] = src[k]; }
  })();
  function bannerOf(name) { return ARTIST_BANNERS[String(name || '').toLowerCase()] || null; }

  var TOURS = window.TOUR_DATA || {};
  function tourOf(s) {
    return s.tourName || TOURS[s.headliner + '|' + (s.date || '') + '|' + s.venueRaw] || null;
  }

  // ------------------------------------------------------------------ badges
  var CITY_COORDS = {
    'Baltimore|MD':       [39.2904, -76.6122],
    'Bloomington|IN':     [39.1653, -86.5264],
    'Cabo San Lucas|MX':  [22.8905, -109.9167],
    'Carmel|IN':          [39.9784, -86.1180],
    'Chicago|IL':         [41.8781, -87.6298],
    'Cincinnati|OH':      [39.1031, -84.5120],
    'Cincinatti|OH':      [39.1031, -84.5120],
    'Cleveland|OH':       [41.4993, -81.6944],
    'Columbia|MD':        [39.2037, -76.8610],
    'Columbus|OH':        [39.9612, -82.9988],
    'Fishers|IN':         [39.9578, -85.9683],
    'Ft. Wayne|IN':       [41.0793, -85.1394],
    'Indianapolis|IN':    [39.7684, -86.1581],
    'Merrillville|IN':    [41.4745, -87.3325],
    'Merrilville|IN':     [41.4745, -87.3325],
    'Milwaukee|WI':       [43.0389, -88.0326],
    'Morrison|CO':        [39.6533, -105.1911],
    'Nashville|IN':       [39.2059, -86.2472],
    'Noblesville|IN':     [40.0456, -85.9066],
    'Phoenix|AZ':         [33.4484, -112.0740],
    'South Bend|IN':      [41.6764, -86.2520],
    'West Lafayette|IN':  [40.4259, -86.9081],
  };
  var HOME_COORDS = [39.9578, -85.9683]; // Fishers, IN

  function haversineMiles(lat1, lon1, lat2, lon2) {
    var R = 3959, rad = Math.PI / 180;
    var dLat = (lat2 - lat1) * rad, dLon = (lon2 - lon1) * rad;
    var a = Math.sin(dLat / 2) * Math.sin(dLat / 2) +
            Math.cos(lat1 * rad) * Math.cos(lat2 * rad) *
            Math.sin(dLon / 2) * Math.sin(dLon / 2);
    return R * 2 * Math.atan2(Math.sqrt(a), Math.sqrt(1 - a));
  }

  var BADGE_DEFS = {
    'superfan':      { icon: '⭐', label: 'Superfan',          desc: 'Seen 10+ times' },
    'superfan-gold': { icon: '🌟', label: 'Legend',            desc: 'Seen 20+ times' },
    'road-trip':     { icon: '🚗', label: 'Road Trip',         desc: '250+ miles from home' },
    'gone-distance': { icon: '✈️', label: 'Gone the Distance', desc: '500+ miles from home' },
    'passport':      { icon: '🌎', label: 'Passport Stamped',  desc: 'Show outside the US' },
    'final-bow':     { icon: '🕯️', label: 'Final Bow',         desc: 'Artist no longer performs' },
    'opener-effect': { icon: '🚀', label: 'Opener Effect',     desc: 'Spotted them before they made it big' },
  };

  var US_STATES = 'AL AK AZ AR CA CO CT DE FL GA HI ID IL IN IA KS KY LA ME MD MA MI MN MS MO MT NE NV NH NJ NM NY NC ND OH OK OR PA RI SC SD TN TX UT VT VA WA WV WI WY DC'.split(' ');
  var RETIRED = (window.CONCERT_CONFIG && window.CONCERT_CONFIG.retiredArtists) || {};

  var ARTIST_PHOTOS = {};
  (function () {
    var src = (window.CONCERT_CONFIG && window.CONCERT_CONFIG.artistPhotos) || {};
    for (var k in src) { if (src.hasOwnProperty(k)) ARTIST_PHOTOS[k.toLowerCase()] = src[k]; }
  })();
  function photoOf(name) { return ARTIST_PHOTOS[String(name || "").toLowerCase()] || null; }

  // group (artist) -> shows (any slot), sorted chronologically
  var bandIndex = {};   // group name -> [shows]
  SHOWS.forEach(function (s) {
    var seen = {};
    s.bands.forEach(function (b) {
      if (!b) return;
      var g = groupOf(b);
      if (seen[g]) return;   // count an artist once per show, even across name variants
      seen[g] = 1;
      (bandIndex[g] = bandIndex[g] || []).push(s);
    });
  });
  Object.keys(bandIndex).forEach(function (k) {
    bandIndex[k].sort(function (a, b) {
      var ad = a.date || "9999", bd = b.date || "9999";
      return ad < bd ? -1 : ad > bd ? 1 : a.id - b.id;
    });
  });

  // venue -> shows
  var venueIndex = {};
  SHOWS.forEach(function (s) {
    if (!s.venue) return;
    (venueIndex[s.venue] = venueIndex[s.venue] || []).push(s);
  });
  Object.keys(venueIndex).forEach(function (k) {
    venueIndex[k].sort(function (a, b) {
      var ad = a.date || "9999", bd = b.date || "9999";
      return ad < bd ? -1 : ad > bd ? 1 : a.id - b.id;
    });
  });

  function countList(index) {
    return Object.keys(index).map(function (k) {
      return { name: k, count: index[k].length };
    }).sort(function (a, b) {
      return b.count - a.count || a.name.localeCompare(b.name);
    });
  }
  var ARTISTS = countList(bandIndex);
  var VENUES  = countList(venueIndex);

  // ---- compute per-show badges -------------------------------------------
  var headlinerFirstDate = {};
  DATED.forEach(function (s) {
    var hg = groupOf(s.headliner);
    if (!headlinerFirstDate[hg] || s.date < headlinerFirstDate[hg]) headlinerFirstDate[hg] = s.date;
  });

  SHOWS.forEach(function (s) {
    s.badges = [];
    var coords = CITY_COORDS[(s.city || '') + '|' + (s.state || '')];
    s.distMiles = coords ? Math.round(haversineMiles(HOME_COORDS[0], HOME_COORDS[1], coords[0], coords[1])) : null;
    if (s.distMiles >= 500)      s.badges.push('gone-distance');
    else if (s.distMiles >= 250) s.badges.push('road-trip');
    if (s.state && US_STATES.indexOf(s.state) === -1) s.badges.push('passport');
    if (RETIRED[groupOf(s.headliner)]) s.badges.push('final-bow');
    if (s.date) {
      var hasOpener = s.bands.some(function (b) {
        if (groupOf(b) === groupOf(s.headliner)) return false;
        var bg = groupOf(b);
        return headlinerFirstDate[bg] && headlinerFirstDate[bg] > s.date;
      });
      if (hasOpener) s.badges.push('opener-effect');
    }
  });

  var superfanGroups = {};
  Object.keys(bandIndex).forEach(function (g) { superfanGroups[g] = bandIndex[g].length; });

  // ---- song frequency (from shows with setlist data) ---------------------
  var SONG_COUNTS = {};
  var SKIP_SONG = /\bsolo\b|\bintro\b|\boutro\b/i;
  SHOWS.forEach(function (s) {
    (s.songs || []).forEach(function (song) {
      if (song && !SKIP_SONG.test(song)) {
        SONG_COUNTS[song] = (SONG_COUNTS[song] || 0) + 1;
      }
    });
  });
  var TOP_SONGS = Object.keys(SONG_COUNTS)
    .map(function (s) { return { name: s, count: SONG_COUNTS[s] }; })
    .sort(function (a, b) { return b.count - a.count || a.name.localeCompare(b.name); });
  var SHOWS_WITH_SONGS = SHOWS.filter(function (s) { return s.songs && s.songs.length; }).length;

  // years
  var yearCounts = {};
  SHOWS.forEach(function (s) { if (s.year) yearCounts[s.year] = (yearCounts[s.year] || 0) + 1; });
  var YEARS = Object.keys(yearCounts).map(Number).sort(function (a, b) { return a - b; });

  // nth time an artist (group) appears, as of a given show
  function nthSeen(band, show) {
    var list = bandIndex[groupOf(band)] || [];
    for (var i = 0; i < list.length; i++) if (list[i].id === show.id) return i + 1;
    return null;
  }

  // ------------------------------------------------------- render: ticket
  // Venue name links to its detail page; the current venue (on its own page) is
  // shown bold with no self-link.
  function venueLine(s, venueHighlight) {
    var loc = [s.city, s.state].filter(Boolean).join(", ");
    var v;
    if (!s.venue) {
      v = "Venue unknown";
    } else if (venueHighlight && s.venue === venueHighlight) {
      v = '<b>' + esc(s.venue) + '</b>';
    } else if (venueIndex[s.venue]) {
      v = '<button type="button" class="venue-link" data-venue="' + esc(s.venue) + '">' +
          esc(s.venue) + '</button>';
    } else {
      v = esc(s.venue);
    }
    return '<div class="venue">' + v +
           (loc ? ' <span class="city">&middot; ' + esc(loc) + '</span>' : '') + '</div>';
  }
  // Render a band name: shows the original name, but links to / groups under its
  // artist. The current artist (group) is shown bold with no self-link.
  function bandTag(name, highlight) {
    var g = groupOf(name);
    if (highlight && g === highlight) return '<b>' + esc(name) + '</b>';
    if (bandIndex[g]) {
      return '<button type="button" class="band-link" data-artist="' + esc(g) + '">' +
             esc(name) + '</button>';
    }
    return esc(name);
  }
  function tourLine(s) {
    var t = tourOf(s);
    return t ? '<div class="tour-name">' + esc(t) + '</div>' : '';
  }
  function supportLine(s, highlight) {
    var support = s.bands.slice(1);
    if (!support.length) return "";
    var html = support.map(function (b) { return bandTag(b, highlight); }).join(", ");
    return '<div class="support"><span class="w">w/</span> ' + html + '</div>';
  }
  // Build a setlist.fm search link for a show (artist + city + year gives the
  // best shot at landing on the exact setlist; no API key / fully offline).
  function setlistUrl(s) {
    var terms = [s.headliner];
    if (s.city) terms.push(s.city);
    if (s.year) terms.push(s.year);
    return "https://www.setlist.fm/search?query=" + encodeURIComponent(terms.join(" "));
  }
  function setlistLink(s) {
    if (!s.headliner) return "";
    if (s.setlistUrl) {
      // exact setlist page resolved at build time
      return '<a class="setlist-link is-direct" href="' + esc(s.setlistUrl) + '" target="_blank" ' +
             'rel="noopener noreferrer" title="Open this exact setlist on setlist.fm">' +
             'setlist <span class="ext">&#8599;</span></a>';
    }
    return '<a class="setlist-link" href="' + setlistUrl(s) + '" target="_blank" ' +
           'rel="noopener noreferrer" title="Search for this setlist on setlist.fm">' +
           'setlist.fm <span class="ext">&#8599;</span></a>';
  }
  function showBadgeHtml(s) {
    if (!s.badges || !s.badges.length) return '';
    return '<div class="show-badges">' +
      s.badges.map(function (id) {
        var def = BADGE_DEFS[id] || {};
        var title = def.label || id;
        if ((id === 'road-trip' || id === 'gone-distance') && s.distMiles) title += ' (' + s.distMiles + ' mi)';
        if (id === 'final-bow' && RETIRED[groupOf(s.headliner)]) title += ' — ' + RETIRED[groupOf(s.headliner)];
        return '<span class="show-badge" data-badge="' + id + '" title="' + esc(title) + '" role="button" tabindex="0">' + (def.icon || '?') + '</span>';
      }).join('') +
    '</div>';
  }

  function ticketCard(s, opts) {
    opts = opts || {};
    var stub;
    if (s.date) {
      stub = '<div class="mo">' + MONTHS[s.month - 1] + '</div>' +
             '<div class="day">' + s.day + '</div>' +
             '<div class="yr">' + s.year + '</div>';
    } else {
      stub = '<div class="nodate">YEAR</div><div class="day" style="font-size:22px">' +
             (s.year || "??") + '</div>';
    }
    var badge = opts.badge ? '<div class="badge">' + esc(opts.badge) + '</div>' : '';
    var hl = opts.highlight;
    var hg = groupOf(s.headliner);
    var head;
    if (hl && hg === hl) {
      head = '<span style="color:var(--red)">' + esc(s.headliner) + '</span>';
    } else if (bandIndex[hg]) {
      head = '<button type="button" class="band-link" data-artist="' + esc(hg) + '">' +
             esc(s.headliner) + '</button>';
    } else {
      head = esc(s.headliner);
    }
    return '<div class="ticket">' +
             '<div class="stub">' + stub + '</div>' +
             '<div class="body">' + badge + showBadgeHtml(s) +
               '<div class="headliner">' + head + '</div>' +
               supportLine(s, hl) +
               tourLine(s) +
               venueLine(s, opts.venueHighlight) +
               '<div class="ticket-foot"><div class="barcode"></div>' + setlistLink(s) + '</div>' +
             '</div>' +
           '</div>';
  }
  function ticketsHtml(list, opts) {
    if (!list.length) return '<div class="empty">No shows to show here.</div>';
    return '<div class="tickets">' + list.map(function (s) { return ticketCard(s, opts); }).join("") + '</div>';
  }

  // ------------------------------------------------------- render: charts
  function barChartVertical(data, opts) {
    opts = opts || {};
    var W = 760, H = 240, padL = 30, padB = 34, padT = 14, padR = 8;
    var n = data.length;
    var max = Math.max.apply(null, data.map(function (d) { return d.value; }).concat([1]));
    var plotW = W - padL - padR, plotH = H - padT - padB;
    var bw = plotW / n;
    var bars = data.map(function (d, i) {
      var h = max ? (d.value / max) * plotH : 0;
      var x = padL + i * bw + bw * 0.12;
      var w = bw * 0.76;
      var y = padT + plotH - h;
      var lbl = (n <= 18 || i % 2 === 0)
        ? '<text class="axis-text" x="' + (x + w / 2) + '" y="' + (H - padB + 14) +
          '" text-anchor="middle" transform="rotate(0 ' + (x + w / 2) + ' ' + (H - padB + 14) + ')">' +
          esc(d.label) + '</text>'
        : '';
      var val = d.value > 0
        ? '<text class="val-text" x="' + (x + w / 2) + '" y="' + (y - 3) + '" text-anchor="middle">' + d.value + '</text>'
        : '';
      return '<rect class="bar-rect' + (opts.alt ? ' alt' : '') + '" x="' + x + '" y="' + y +
             '" width="' + w + '" height="' + h + '" rx="2"></rect>' + val + lbl;
    }).join("");
    var axis = '<line class="axis" x1="' + padL + '" y1="' + (padT + plotH) + '" x2="' + (W - padR) +
               '" y2="' + (padT + plotH) + '"></line>';
    return '<svg viewBox="0 0 ' + W + ' ' + H + '" preserveAspectRatio="xMidYMid meet">' + axis + bars + '</svg>';
  }

  function lineChart(data) {
    var W = 760, H = 220, padL = 36, padB = 34, padT = 14, padR = 10;
    var n = data.length;
    var max = Math.max.apply(null, data.map(function (d) { return d.value; }).concat([1]));
    var plotW = W - padL - padR, plotH = H - padT - padB;
    var xFor = function (i) { return padL + (n <= 1 ? plotW / 2 : (i / (n - 1)) * plotW); };
    var yFor = function (v) { return padT + plotH - (v / max) * plotH; };
    var d = data.map(function (p, i) { return (i ? "L" : "M") + xFor(i) + " " + yFor(p.value); }).join(" ");
    var dots = data.map(function (p, i) {
      return '<circle class="line-dot" cx="' + xFor(i) + '" cy="' + yFor(p.value) + '" r="3"></circle>';
    }).join("");
    var labels = data.map(function (p, i) {
      if (!(n <= 18 || i % 3 === 0 || i === n - 1)) return "";
      return '<text class="axis-text" x="' + xFor(i) + '" y="' + (H - padB + 16) + '" text-anchor="middle">' +
             esc(p.label) + '</text>';
    }).join("");
    var endVal = '<text class="val-text" x="' + xFor(n - 1) + '" y="' + (yFor(data[n - 1].value) - 8) +
                 '" text-anchor="end">' + data[n - 1].value + '</text>';
    var axis = '<line class="axis" x1="' + padL + '" y1="' + (padT + plotH) + '" x2="' + (W - padR) +
               '" y2="' + (padT + plotH) + '"></line>';
    return '<svg viewBox="0 0 ' + W + ' ' + H + '" preserveAspectRatio="xMidYMid meet">' +
           axis + '<path class="line-path" d="' + d + '"></path>' + dots + endVal + labels + '</svg>';
  }

  // horizontal bars for top lists
  function barChartHorizontal(data, opts) {
    opts = opts || {};
    var rowH = 26, padL = 6, padR = 40, labelW = 200, W = 760;
    var H = data.length * rowH + 8;
    var max = Math.max.apply(null, data.map(function (d) { return d.value; }).concat([1]));
    var plotW = W - labelW - padL - padR;
    var rows = data.map(function (d, i) {
      var y = i * rowH + 4;
      var w = (d.value / max) * plotW;
      return '<text class="axis-text" x="' + (labelW - 8) + '" y="' + (y + rowH / 2 + 3) +
               '" text-anchor="end" style="font-size:11px;fill:var(--ink)">' + esc(trunc(d.label, 26)) + '</text>' +
             '<rect class="bar-rect' + (opts.alt ? ' alt' : '') + '" x="' + labelW + '" y="' + (y + 4) +
               '" width="' + Math.max(w, 1) + '" height="' + (rowH - 10) + '" rx="2"></rect>' +
             '<text class="val-text" x="' + (labelW + w + 6) + '" y="' + (y + rowH / 2 + 3) + '">' + d.value + '</text>';
    }).join("");
    return '<svg viewBox="0 0 ' + W + ' ' + H + '" preserveAspectRatio="xMidYMid meet">' + rows + '</svg>';
  }
  function trunc(s, n) { s = String(s); return s.length > n ? s.slice(0, n - 1) + "…" : s; }

  // --------------------------------------------------------------- views
  var app = el("app");

  function rowItem(rank, name, count, maxCount, kind) {
    var thumb = (kind === "artist" && photoOf(name))
      ? '<img class="artist-thumb" src="' + esc(photoOf(name)) + '" alt="" aria-hidden="true">'
      : '';
    return '<button class="rowitem" data-kind="' + kind + '" data-name="' + esc(name) + '">' +
             '<span class="rank">' + rank + '</span>' +
             thumb +
             '<span class="name" title="' + esc(name) + '">' + esc(name) + '</span>' +
             '<span class="cnt">' + count + '<span class="x">&times;</span></span>' +
           '</button>';
  }

  function viewOverview() {
    var uniqueArtists = ARTISTS.length;
    var uniqueVenues = VENUES.length;
    var firstYear = YEARS[0], lastYear = YEARS[YEARS.length - 1];
    var thisYear = new Date().getFullYear();
    var showsThisYear = yearCounts[thisYear] || 0;

    var tiles =
      tile(SHOWS.length, "Total shows", "accent") +
      tile(uniqueArtists, "Bands seen") +
      tile(uniqueVenues, "Venues") +
      tile((lastYear - firstYear + 1), "Years active", "accent2") +
      tile(showsThisYear, "Shows in " + thisYear);

    var maxA = ARTISTS[0] ? ARTISTS[0].count : 1;
    var topA = ARTISTS.slice(0, 10).map(function (a, i) {
      return rowItem(i + 1, a.name, a.count, maxA, "artist");
    }).join("");
    var maxV = VENUES[0] ? VENUES[0].count : 1;
    var topV = VENUES.slice(0, 10).map(function (v, i) {
      return rowItem(i + 1, v.name, v.count, maxV, "venue");
    }).join("");

    app.innerHTML =
      '<div class="view-head">The Stats <span class="count-pill">since ' + firstYear + '</span></div>' +
      '<div class="tiles">' + tiles + '</div>' +
      buildAchievements() +
      '<div class="cols2" style="margin-top:30px">' +
        '<div><div class="view-head">Most-seen bands</div><div class="rowlist">' + topA + '</div></div>' +
        '<div><div class="view-head">Most-visited venues</div><div class="rowlist">' + topV + '</div></div>' +
      '</div>';
    wireRows();
  }
  function tile(num, label, cls) {
    return '<div class="tile ' + (cls || "") + '"><div class="num">' + num + '</div>' +
           '<div class="label">' + esc(label) + '</div></div>';
  }

  // ---- On This Day -------------------------------------------------------
  var otdDate = null;  // {m, d} currently viewed
  function viewOnThisDay() {
    var today = otdDate || (function () { var n = new Date(); return { m: n.getMonth() + 1, d: n.getDate() }; })();
    var matches = DATED.filter(function (s) { return s.month === today.m && s.day === today.d; })
                       .sort(function (a, b) { return b.year - a.year; });

    var dateInput = '<input type="date" id="otd-picker" />';
    var head =
      '<div class="view-head">On This Day &mdash; ' + MONTHS_LONG[today.m - 1] + ' ' + today.d +
        '<span class="count-pill">' + matches.length + ' show' + (matches.length === 1 ? "" : "s") + '</span>' +
      '</div>' +
      '<div class="search-controls"><span class="chip" style="cursor:default">Jump to a date:</span>' + dateInput +
        '<button class="chip" id="otd-today">Today</button></div>';

    var body;
    if (!matches.length) {
      body = '<div class="empty">No shows on ' + MONTHS_LONG[today.m - 1] + ' ' + today.d +
             ' &mdash; yet. Try another date above.</div>';
    } else {
      // milestone callouts
      var miles = [];
      matches.forEach(function (s) {
        if (s.ordinal % 50 === 0 || s.ordinal === 1 || s.ordinal === 25 || s.ordinal === 100 ||
            s.ordinal === 200 || s.ordinal === 300) {
          miles.push(milestone("Milestone show",
            "On this date in <b>" + s.year + "</b> you saw your <b>" + ordinal(s.ordinal) +
            " show ever</b> &mdash; " + esc(s.headliner) + "."));
        }
        var nth = nthSeen(s.headliner, s);
        var gname = groupOf(s.headliner);   // count is grouped, so name the artist
        if (nth === 1) {
          miles.push(milestone("First time",
            "On this date in <b>" + s.year + "</b> you saw <b>" + esc(gname) +
            "</b> for the first time."));
        } else if (nth && nth % 5 === 0) {
          miles.push(milestone("Repeat offender",
            "This was your <b>" + ordinal(nth) + " time</b> seeing <b>" + esc(gname) +
            "</b> (" + s.year + ")."));
        }
      });
      body = miles.join("") + ticketsHtml(matches);
    }
    app.innerHTML = head + body;

    var picker = el("otd-picker");
    if (picker) {
      // show current date in the picker (use a representative recent year)
      var yyyy = new Date().getFullYear();
      picker.value = yyyy + "-" + pad2(today.m) + "-" + pad2(today.d);
      picker.addEventListener("change", function () {
        var p = parts(picker.value);
        if (p) { otdDate = { m: p.m, d: p.d }; viewOnThisDay(); }
      });
    }
    var tbtn = el("otd-today");
    if (tbtn) tbtn.addEventListener("click", function () { otdDate = null; viewOnThisDay(); });
  }
  function pad2(n) { return (n < 10 ? "0" : "") + n; }
  function milestone(tag, txt) {
    return '<div class="milestone"><div class="tag">' + esc(tag) + '</div><div class="txt">' + txt + '</div></div>';
  }

  // ---- Artists / Venues lists -------------------------------------------
  function viewArtists() { listView("artist", ARTISTS, "Bands", "times seen"); }
  function viewVenues()  { listView("venue", VENUES, "Venues", "visits"); }

  function listView(kind, data, title, unit) {
    var max = data[0] ? data[0].count : 1;
    app.innerHTML =
      '<div class="view-head">' + title + '<span class="count-pill">' + data.length + ' total</span></div>' +
      '<div class="searchbar"><input id="list-filter" placeholder="Filter ' + title.toLowerCase() +
        '&hellip;" autocomplete="off" /></div>' +
      '<div class="rowlist" id="list-rows"></div>';
    var rowsEl = el("list-rows");
    function paint(q) {
      q = (q || "").toLowerCase();
      var filtered = data.filter(function (d) { return d.name.toLowerCase().indexOf(q) >= 0; });
      rowsEl.innerHTML = filtered.length
        ? filtered.map(function (d, i) { return rowItem(i + 1, d.name, d.count, max, kind); }).join("")
        : '<div class="empty">No ' + title.toLowerCase() + ' match &ldquo;' + esc(q) + '&rdquo;.</div>';
      wireRows();
    }
    paint("");
    el("list-filter").addEventListener("input", function (e) { paint(e.target.value); });
  }

  // ---- detail (artist or venue) -----------------------------------------
  function showDetail(kind, name) {
    var list = (kind === "artist" ? bandIndex[name] : venueIndex[name]) || [];
    var dated = list.filter(function (s) { return s.date; });
    var first = dated[0], last = dated[dated.length - 1];
    var stat = [];
    stat.push("<b>" + list.length + "</b> " + (kind === "artist" ? "show" + (list.length === 1 ? "" : "s") : "visit" + (list.length === 1 ? "" : "s")));
    if (first) stat.push("first: <b>" + prettyDate(first.date) + "</b>");
    if (last && last !== first) stat.push("latest: <b>" + prettyDate(last.date) + "</b>");
    if (kind === "artist") {
      var venuesForArtist = {};
      list.forEach(function (s) { if (s.venue) venuesForArtist[s.venue] = 1; });
      stat.push("<b>" + Object.keys(venuesForArtist).length + "</b> venue(s)");
    } else {
      var bandsAtVenue = {};
      list.forEach(function (s) { s.bands.forEach(function (b) { bandsAtVenue[b] = 1; }); });
      stat.push("<b>" + Object.keys(bandsAtVenue).length + "</b> different band(s)");
    }
    // venue "also known as" callout -- union of former/other names across its shows
    var akaHtml = "";
    if (kind === "venue") {
      var akaSeen = {}, akaList = [];
      list.forEach(function (s) {
        (s.venueAka || []).forEach(function (a) {
          var key = a.toLowerCase();
          if (a && !akaSeen[key]) { akaSeen[key] = 1; akaList.push(a); }
        });
      });
      if (akaList.length) {
        akaHtml = '<div class="aka"><span class="aka-tag">also known as</span> ' +
          akaList.map(function (a) { return esc(a); }).join(" &middot; ") + '</div>';
      }
    }
    var ordered = list.slice().sort(function (a, b) {
      var ad = a.date || "0000", bd = b.date || "0000";
      return ad > bd ? -1 : ad < bd ? 1 : b.id - a.id;   // newest first
    });
    var detailPhoto = (kind === "artist" && photoOf(name))
      ? '<img class="artist-photo" src="' + esc(photoOf(name)) + '" alt="' + esc(name) + '">'
      : '';
    var banner = (kind === "artist") ? bannerOf(name) : null;
    var bannerStyle = banner
      ? ' style="background-image:url(\'' + esc(banner) + '\');background-size:cover;background-position:right center;"'
      : '';
    app.innerHTML =
      '<div class="detail-head' + (banner ? ' detail-head-banner' : '') + '"' + bannerStyle + '>' +
        (detailPhoto ? '<div class="detail-head-inner">' : '') +
        '<div class="detail-head-text">' +
          '<button class="back" id="detail-back">&larr; back</button>' +
          '<h2>' + esc(name) + '</h2>' +
          (kind === 'artist' && superfanGroups[name] >= 20 ? '<div class="superfan-badge">🌟 Legend</div>' : '') +
          (kind === 'artist' && superfanGroups[name] >= 10 && superfanGroups[name] < 20 ? '<div class="superfan-badge">⭐ Superfan</div>' : '') +
          akaHtml +
          '<div class="stat-line">' + stat.map(function (x) { return "<span>" + x + "</span>"; }).join("") + '</div>' +
        '</div>' +
        detailPhoto +
        (detailPhoto ? '</div>' : '') +
      '</div>' +
      ticketsHtml(ordered, {
        highlight: kind === "artist" ? name : null,
        venueHighlight: kind === "venue" ? name : null
      });
    el("detail-back").addEventListener("click", function () {
      setView(kind === "artist" ? "artists" : "venues");
    });
  }

  function wireRows() {
    Array.prototype.forEach.call(document.querySelectorAll(".rowitem"), function (b) {
      b.addEventListener("click", function () {
        showDetail(b.getAttribute("data-kind"), b.getAttribute("data-name"));
      });
    });
    Array.prototype.forEach.call(document.querySelectorAll(".show-badge"), function (b) {
      b.addEventListener("click", function (e) {
        e.stopPropagation();
        viewBadge(b.getAttribute("data-badge"));
      });
    });
    Array.prototype.forEach.call(document.querySelectorAll(".achievement"), function (b) {
      b.addEventListener("click", function () {
        viewBadge(b.getAttribute("data-achievement"));
      });
    });
  }

  function buildAchievements() {
    var defs = [
      { id: 'superfan-gold', count: Object.keys(superfanGroups).filter(function (g) { return superfanGroups[g] >= 20; }).length, unit: 'artist' },
      { id: 'superfan',      count: Object.keys(superfanGroups).filter(function (g) { return superfanGroups[g] >= 10; }).length, unit: 'artist' },
      { id: 'opener-effect', count: SHOWS.filter(function (s) { return s.badges.indexOf('opener-effect') >= 0; }).length, unit: 'show' },
      { id: 'gone-distance', count: SHOWS.filter(function (s) { return s.badges.indexOf('gone-distance') >= 0; }).length, unit: 'show' },
      { id: 'road-trip',     count: SHOWS.filter(function (s) { return s.badges.indexOf('road-trip') >= 0; }).length, unit: 'show' },
      { id: 'passport',      count: SHOWS.filter(function (s) { return s.badges.indexOf('passport') >= 0; }).length, unit: 'show' },
      { id: 'final-bow',     count: SHOWS.filter(function (s) { return s.badges.indexOf('final-bow') >= 0; }).length, unit: 'show' },
    ].filter(function (d) { return d.count > 0; });

    if (!defs.length) return '';
    return '<div class="view-head" style="margin-top:28px">Achievements</div>' +
      '<div class="achievement-grid">' +
      defs.map(function (d) {
        var def = BADGE_DEFS[d.id];
        return '<button class="achievement" data-achievement="' + d.id + '" title="' + esc(def.desc) + '">' +
                 '<span class="ach-icon">' + def.icon + '</span>' +
                 '<span class="ach-name">' + esc(def.label) + '</span>' +
                 '<span class="ach-count">' + d.count + ' ' + d.unit + (d.count !== 1 ? 's' : '') + '</span>' +
               '</button>';
      }).join('') +
      '</div>';
  }

  function viewBadge(id) {
    var def = BADGE_DEFS[id];
    if (!def) return;

    if (id === 'superfan' || id === 'superfan-gold') {
      var minCount = id === 'superfan-gold' ? 20 : 10;
      var artists = Object.keys(superfanGroups)
        .filter(function (g) { return superfanGroups[g] >= minCount; })
        .sort(function (a, b) { return superfanGroups[b] - superfanGroups[a]; });
      var maxC = artists.length ? superfanGroups[artists[0]] : 1;
      var rows = artists.map(function (g, i) {
        return rowItem(i + 1, g, superfanGroups[g], maxC, 'artist');
      }).join('');
      app.innerHTML =
        '<div class="detail-head"><div class="detail-head-text">' +
          '<button class="back" id="badge-back">&larr; back</button>' +
          '<h2>' + def.icon + ' ' + def.label + '</h2>' +
          '<div class="stat-line"><span>' + def.desc + '</span> &middot; <span>' +
            artists.length + ' artist' + (artists.length !== 1 ? 's' : '') + '</span></div>' +
        '</div></div>' +
        '<div class="rowlist">' + rows + '</div>';
      el('badge-back').addEventListener('click', function () { setView('overview'); });
      wireRows();
      return;
    }

    var list = SHOWS.filter(function (s) { return s.badges && s.badges.indexOf(id) >= 0; });
    list = list.slice().sort(function (a, b) { return (a.date || '') < (b.date || '') ? 1 : -1; });

    var extra = '';
    if (id === 'final-bow') {
      var retiredSeen = {};
      list.forEach(function (s) {
        var g = groupOf(s.headliner);
        if (!retiredSeen[g]) retiredSeen[g] = { reason: RETIRED[g] || '', count: 0 };
        retiredSeen[g].count++;
      });
      extra = '<div class="badge-artists">' +
        Object.keys(retiredSeen).map(function (g) {
          var r = retiredSeen[g];
          return '<div class="badge-artist-row">' +
                   '<strong>' + esc(g) + '</strong>' +
                   (r.reason ? ' &mdash; ' + esc(r.reason) : '') + ' ' +
                   '<span class="badge-count">(' + r.count + ' show' + (r.count !== 1 ? 's' : '') + ')</span>' +
                 '</div>';
        }).join('') +
      '</div>';
    } else if (id === 'opener-effect') {
      extra = '<div class="badge-note">These shows had a supporting act who later headlined your concert list.</div>';
    }

    app.innerHTML =
      '<div class="detail-head"><div class="detail-head-text">' +
        '<button class="back" id="badge-back">&larr; back</button>' +
        '<h2>' + def.icon + ' ' + def.label + '</h2>' +
        '<div class="stat-line"><span>' + def.desc + '</span> &middot; <span>' +
          list.length + ' show' + (list.length !== 1 ? 's' : '') + '</span></div>' +
      '</div></div>' +
      extra +
      ticketsHtml(list, {});
    el('badge-back').addEventListener('click', function () { setView('overview'); });
    wireRows();
  }

  // ---- Timeline / charts -------------------------------------------------
  function viewTimeline() {
    var perYear = YEARS.map(function (y) { return { label: String(y), value: yearCounts[y] }; });
    var cum = 0;
    var cumData = YEARS.map(function (y) { cum += yearCounts[y]; return { label: String(y), value: cum }; });
    var topA = ARTISTS.slice(0, 12).map(function (a) { return { label: a.name, value: a.count }; });
    var topV = VENUES.slice(0, 12).map(function (v) { return { label: v.name, value: v.count }; });

    app.innerHTML =
      '<div class="chart-card"><h3>Shows per year</h3>' + barChartVertical(perYear) + '</div>' +
      '<div class="chart-card"><h3>Cumulative shows over time</h3>' + lineChart(cumData) + '</div>' +
      '<div class="cols2">' +
        '<div class="chart-card"><h3>Top bands</h3>' + barChartHorizontal(topA) + '</div>' +
        '<div class="chart-card"><h3>Top venues</h3>' + barChartHorizontal(topV, { alt: true }) + '</div>' +
      '</div>' +
      (TOP_SONGS.length
        ? '<div class="chart-card"><h3>Most Heard Songs Live (According to Setlist.fm)</h3>' +
            barChartHorizontal(TOP_SONGS.slice(0, 15).map(function (s) { return { label: s.name, value: s.count }; })) +
          '</div>'
        : '') +
      funStats();
    wireFacts();
  }

  // ---- Fun stats ---------------------------------------------------------
  function funStats() {
    var facts = [];
    // busiest year
    var busiest = YEARS.slice().sort(function (a, b) { return yearCounts[b] - yearCounts[a]; })[0];
    facts.push(fact("Busiest year", busiest, yearCounts[busiest] + " shows", {nav: 'year', year: busiest}));
    // average per active year
    var avg = (SHOWS.length / YEARS.length).toFixed(1);
    facts.push(fact("Avg / active year", avg, "shows per year"));
    // most-seen decade
    var dec = {};
    SHOWS.forEach(function (s) { if (s.year) { var d = Math.floor(s.year / 10) * 10; dec[d] = (dec[d] || 0) + 1; } });
    var topDec = Object.keys(dec).sort(function (a, b) { return dec[b] - dec[a]; })[0];
    facts.push(fact("Top decade", topDec + "s", dec[topDec] + " shows"));
    // first show
    if (DATED[0]) facts.push(fact("First show ever", DATED[0].headliner, prettyDate(DATED[0].date), {nav: 'artist', name: groupOf(DATED[0].headliner)}));
    // longest gap between shows
    var gap = longestGap();
    if (gap) {
      var gapTo = gap.to.split('-');
      facts.push(fact("Longest dry spell", gap.days + " days", prettyDate(gap.from) + " → " + prettyDate(gap.to),
        {nav: 'otd', month: +gapTo[1], day: +gapTo[2]}));
    }
    // most-heard song
    if (TOP_SONGS[0]) {
      facts.push(fact("Most-heard song", TOP_SONGS[0].name, TOP_SONGS[0].count + " times live",
        { nav: 'song', name: TOP_SONGS[0].name }));
    }
    // bands seen once
    var once = ARTISTS.filter(function (a) { return a.count === 1; }).length;
    facts.push(fact("One-and-done bands", once, "seen exactly once"));
    // most concerts in a single month
    var monthCount = {};
    DATED.forEach(function (s) {
      if (s.year && s.month) {
        var mk = s.year + '-' + s.month;
        monthCount[mk] = (monthCount[mk] || 0) + 1;
      }
    });
    var topMonthKey = Object.keys(monthCount).sort(function (a, b) { return monthCount[b] - monthCount[a]; })[0];
    if (topMonthKey) {
      var tmParts = topMonthKey.split('-');
      var tmYear = +tmParts[0], tmMonth = +tmParts[1];
      facts.push(fact("Biggest month", MONTHS_LONG[tmMonth - 1] + " " + tmYear,
        monthCount[topMonthKey] + " shows", {nav: 'year', year: tmYear}));
    }
    // most common state/city
    var stateCount = {};
    SHOWS.forEach(function (s) { if (s.state) stateCount[s.state] = (stateCount[s.state] || 0) + 1; });
    var topState = Object.keys(stateCount).sort(function (a, b) { return stateCount[b] - stateCount[a]; })[0];
    if (topState) facts.push(fact("Home turf", topState, stateCount[topState] + " shows", {nav: 'search', q: topState}));
    // unique states
    var uniqueStates = Object.keys(stateCount).length;
    if (uniqueStates) facts.push(fact("States visited", uniqueStates, "different states"));
    // milestone shows
    [50, 100, 150, 200, 250, 300].forEach(function (m) {
      var s = DATED[m - 1];
      if (s) facts.push(fact(ordinal(m) + " show", s.headliner, prettyDate(s.date), {nav: 'artist', name: groupOf(s.headliner)}));
    });

    return '<div class="view-head">Fun Facts</div><div class="factgrid">' + facts.join("") + '</div>';
  }
  function fact(k, v, sub, nav) {
    var inner = '<div class="k">' + esc(k) + '</div><div class="v">' + esc(v) + '</div>' +
                (sub ? '<div class="sub">' + esc(sub) + '</div>' : '');
    if (!nav) return '<div class="fact">' + inner + '</div>';
    var attrs = 'type="button" class="fact fact-link"';
    for (var key in nav) { if (nav.hasOwnProperty(key)) attrs += ' data-' + key + '="' + esc(String(nav[key])) + '"'; }
    return '<button ' + attrs + '>' + inner + '</button>';
  }
  function wireFacts() {
    Array.prototype.forEach.call(document.querySelectorAll('.fact-link'), function (b) {
      b.addEventListener('click', function () {
        var nav = b.getAttribute('data-nav');
        if (nav === 'artist') {
          showDetail('artist', b.getAttribute('data-name'));
        } else if (nav === 'year') {
          searchState.year = +b.getAttribute('data-year');
          searchState.q = '';
          setView('search');
        } else if (nav === 'otd') {
          otdDate = { m: +b.getAttribute('data-month'), d: +b.getAttribute('data-day') };
          setView('onthisday');
        } else if (nav === 'search') {
          searchState.q = b.getAttribute('data-q');
          searchState.year = null;
          setView('search');
        } else if (nav === 'song') {
          viewSongShows(b.getAttribute('data-name'));
        }
      });
    });
  }

  function viewSongShows(song) {
    var list = SHOWS.filter(function (s) { return (s.songs || []).indexOf(song) >= 0; });
    list = list.slice().sort(function (a, b) { return (a.date || '') < (b.date || '') ? 1 : -1; });
    app.innerHTML =
      '<div class="detail-head"><div class="detail-head-text">' +
        '<button class="back" id="song-back">&larr; back</button>' +
        '<h2>&#127925; ' + esc(song) + '</h2>' +
        '<div class="stat-line"><span>Heard live</span> &middot; <span>' +
          list.length + ' time' + (list.length !== 1 ? 's' : '') + '</span></div>' +
      '</div></div>' +
      ticketsHtml(list, {});
    el('song-back').addEventListener('click', function () { setView('timeline'); });
    wireRows();
  }

  function longestGap() {
    var best = null;
    for (var i = 1; i < DATED.length; i++) {
      var a = new Date(DATED[i - 1].date), b = new Date(DATED[i].date);
      var days = Math.round((b - a) / 86400000);
      if (!best || days > best.days) best = { days: days, from: DATED[i - 1].date, to: DATED[i].date };
    }
    return best;
  }

  // ---- Search ------------------------------------------------------------
  var searchState = { q: "", year: null };
  function viewSearch() {
    var years = YEARS.slice().reverse();
    var chips = '<button class="chip' + (searchState.year ? "" : " is-active") + '" data-year="">All years</button>' +
      years.map(function (y) {
        return '<button class="chip' + (searchState.year === y ? " is-active" : "") +
               '" data-year="' + y + '">' + y + '</button>';
      }).join("");
    app.innerHTML =
      '<div class="view-head">Search the stub box</div>' +
      '<div class="searchbar"><input id="q" placeholder="Search any band, venue, city, or year&hellip;" ' +
        'autocomplete="off" value="' + esc(searchState.q) + '" /></div>' +
      '<div class="search-controls" id="year-chips">' + chips + '</div>' +
      '<div id="results"></div>';
    var input = el("q");
    input.addEventListener("input", function () { searchState.q = input.value; runSearch(); });
    Array.prototype.forEach.call(document.querySelectorAll("#year-chips .chip"), function (c) {
      c.addEventListener("click", function () {
        var y = c.getAttribute("data-year");
        searchState.year = y ? +y : null;
        viewSearch();
      });
    });
    input.focus();
    runSearch();
  }
  function runSearch() {
    var q = searchState.q.trim().toLowerCase();
    var res = SHOWS.filter(function (s) {
      if (searchState.year && s.year !== searchState.year) return false;
      if (!q) return true;
      if (String(s.year).indexOf(q) >= 0) return true;
      if (s.venue.toLowerCase().indexOf(q) >= 0) return true;
      if (s.venueRaw.toLowerCase().indexOf(q) >= 0) return true;   // old/raw venue text
      if (s.venueAka.some(function (a) { return a.toLowerCase().indexOf(q) >= 0; })) return true;
      if ((s.city + " " + s.state).toLowerCase().indexOf(q) >= 0) return true;
      return s.bands.some(function (b) { return b.toLowerCase().indexOf(q) >= 0; });
    }).sort(function (a, b) {
      var ad = a.date || "0000", bd = b.date || "0000";
      return ad > bd ? -1 : ad < bd ? 1 : b.id - a.id;
    });
    var box = el("results");
    box.innerHTML =
      '<div class="view-head" style="margin-top:6px">' +
        (q || searchState.year ? "Results" : "All shows") +
        '<span class="count-pill">' + res.length + ' show' + (res.length === 1 ? "" : "s") + '</span></div>' +
      ticketsHtml(res);
  }

  // --------------------------------------------------------------- router
  var VIEWS = {
    overview: viewOverview,
    onthisday: viewOnThisDay,
    artists: viewArtists,
    venues: viewVenues,
    timeline: viewTimeline,
    search: viewSearch
  };
  function setView(name) {
    CURRENT_VIEW = name || "overview";
    Array.prototype.forEach.call(document.querySelectorAll(".tab, .mobile-nav-item"), function (t) {
      t.classList.toggle("is-active", t.getAttribute("data-view") === name);
    });
    var mn = el("mobile-nav"); var nt = el("nav-toggle");
    if (mn) mn.classList.remove("is-open");
    if (nt) nt.innerHTML = "&#9776;";
    window.scrollTo(0, 0);
    (VIEWS[name] || viewOverview)();
  }

  // --------------------------------------------------------------- themes
  // key === "" is the default (no data-theme attribute). dots = preview swatch.
  var THEMES = [
    { key: "",          name: "Kraft",     dots: ["#b32f2a", "#20283f", "#c98a23"] },
    { key: "sunset",    name: "Sunset",    dots: ["#d63b6b", "#3a1d46", "#e08a1e"] },
    { key: "vinyl",     name: "Vinyl",     dots: ["#356b4f", "#b5871f", "#8a5a2b"] },
    { key: "bluenote",  name: "Blue Note", dots: ["#2f4a8c", "#d2742a", "#3d7c87"] },
    { key: "backstage", name: "Backstage", dots: ["#d7a83c", "#12110e", "#ecc663"] }
  ];
  var THEME_STORE = "concertTrackerTheme";
  function applyTheme(key) {
    if (key) document.documentElement.setAttribute("data-theme", key);
    else document.documentElement.removeAttribute("data-theme");
    try { localStorage.setItem(THEME_STORE, key); } catch (e) {}
    Array.prototype.forEach.call(document.querySelectorAll(".swatch"), function (s) {
      s.classList.toggle("is-active", s.getAttribute("data-theme-key") === key);
    });
  }
  function buildThemePicker() {
    var host = el("theme-picker");
    if (!host) return;
    THEMES.forEach(function (t) {
      var b = document.createElement("button");
      b.className = "swatch";
      b.setAttribute("data-theme-key", t.key);
      b.innerHTML = '<span class="dots">' +
        t.dots.map(function (c) { return '<i style="background:' + c + '"></i>'; }).join("") +
        '</span>' + esc(t.name);
      b.addEventListener("click", function () { applyTheme(t.key); });
      host.appendChild(b);
    });
    var saved = "";
    try { saved = localStorage.getItem(THEME_STORE) || ""; } catch (e) {}
    applyTheme(saved);
  }

  // -------------------------------------------------------- add show: credentials
  var CRED_SETLIST = "concert_setlist_key";
  var CRED_GITHUB  = "concert_github_pat";
  var GITHUB_REPO  = "mattpippenger/concerts";
  var ADDITIONS_PATH = "concerts-additions.json";

  function getCredentials() {
    try {
      return {
        setlistKey: localStorage.getItem(CRED_SETLIST) || "",
        githubPat:  localStorage.getItem(CRED_GITHUB)  || ""
      };
    } catch (e) { return { setlistKey: "", githubPat: "" }; }
  }

  function saveCredentials(setlistKey, githubPat) {
    try {
      localStorage.setItem(CRED_SETLIST, setlistKey);
      localStorage.setItem(CRED_GITHUB,  githubPat);
    } catch (e) {}
  }

  // -------------------------------------------------------- add show: modal
  function openAddModal() {
    var overlay = el("add-modal-overlay");
    if (!overlay) return;
    overlay.classList.add("is-open");
    overlay.setAttribute("aria-hidden", "false");
    var creds = getCredentials();
    if (!creds.setlistKey || !creds.githubPat) {
      renderSettingsScreen();
    } else {
      renderAddForm();
    }
  }

  function closeAddModal() {
    var overlay = el("add-modal-overlay");
    if (!overlay) return;
    overlay.classList.remove("is-open");
    overlay.setAttribute("aria-hidden", "true");
    el("add-modal-body").innerHTML = "";
  }

  function renderSettingsScreen(onSave) {
    var body = el("add-modal-body");
    body.innerHTML =
      '<h2>&#9881; Settings</h2>' +
      '<p style="font-size:0.85rem;color:var(--ink-muted,#888);margin:0 0 16px">Enter your API credentials once. They\'re stored only in this browser.</p>' +
      '<div class="add-settings-field">' +
        '<label>setlist.fm API Key</label>' +
        '<input id="set-setlist-key" type="password" placeholder="paste your key here" autocomplete="off">' +
        '<div class="add-settings-note">Get one free at <a href="https://www.setlist.fm/settings/api" target="_blank" rel="noopener">setlist.fm/settings/api</a></div>' +
      '</div>' +
      '<div class="add-settings-field">' +
        '<label>GitHub Personal Access Token</label>' +
        '<input id="set-github-pat" type="password" placeholder="ghp_..." autocomplete="off">' +
        '<div class="add-settings-note">Create at <a href="https://github.com/settings/tokens" target="_blank" rel="noopener">github.com/settings/tokens</a> &mdash; Fine-grained token, Contents read+write on <b>mattpippenger/concerts</b></div>' +
      '</div>' +
      '<div class="add-btn-row">' +
        '<button class="add-btn add-btn-primary" id="set-save-btn">Save &amp; Continue</button>' +
        '<button class="add-btn add-btn-secondary" id="set-cancel-btn">Cancel</button>' +
      '</div>';

    // pre-fill with stored values if re-opening settings
    var creds = getCredentials();
    el("set-setlist-key").value = creds.setlistKey;
    el("set-github-pat").value  = creds.githubPat;

    el("set-save-btn").addEventListener("click", function () {
      var sk = el("set-setlist-key").value.trim();
      var gp = el("set-github-pat").value.trim();
      if (!sk || !gp) { alert("Both fields are required."); return; }
      saveCredentials(sk, gp);
      if (typeof onSave === "function") onSave();
      else renderAddForm();
    });

    el("set-cancel-btn").addEventListener("click", function () {
      if (typeof onSave === "function") renderAddForm();
      else closeAddModal();
    });
  }

  function renderAddForm() {
    var body = el("add-modal-body");
    body.innerHTML = '<h2>Add Show</h2><p style="color:var(--ink-muted,#888)">Form coming in next task&hellip;</p>';
  }

  // -------------------------------------------------------- additions merge
  var CURRENT_VIEW = "overview";

  function enrichShow(s, idOffset) {
    var p = parts(s.date);
    var pv = resolveVenue(s.venue);
    return {
      id: idOffset,
      headliner: s.headliner || "",
      bands: (s.bands && s.bands.length ? s.bands : [s.headliner]).filter(Boolean),
      date: s.date || null,
      year: s.year || (p ? p.y : null),
      month: p ? p.m : null,
      day: p ? p.d : null,
      venue: pv.name,
      venueAka: pv.aka,
      venueRaw: s.venue || "",
      city: s.city || "",
      state: s.state || "",
      setlistUrl: setlistOverrideFor(s.headliner, s.date) || s.setlistUrl || null,
      songs: s.songs || [],
      tourName: s.tourName || "",
      badges: [],
      distMiles: null,
      fromAdditions: true
    };
  }

  function recomputeDerived() {
    // re-sort DATED
    DATED.length = 0;
    SHOWS.filter(function (s) { return s.date; })
         .sort(function (a, b) { return a.date < b.date ? -1 : a.date > b.date ? 1 : a.id - b.id; })
         .forEach(function (s, i) { DATED.push(s); s.ordinal = i + 1; });

    // recompute badges for new shows only
    SHOWS.forEach(function (s) {
      if (!s.fromAdditions) return;
      s.badges = [];
      var coords = CITY_COORDS[(s.city || '') + '|' + (s.state || '')];
      s.distMiles = coords ? Math.round(haversineMiles(HOME_COORDS[0], HOME_COORDS[1], coords[0], coords[1])) : null;
      if (s.distMiles >= 500)      s.badges.push('gone-distance');
      else if (s.distMiles >= 250) s.badges.push('road-trip');
      if (s.state && US_STATES.indexOf(s.state) === -1) s.badges.push('passport');
      if (RETIRED[groupOf(s.headliner)]) s.badges.push('final-bow');
    });

    // rebuild bandIndex entries for new shows
    SHOWS.forEach(function (s) {
      if (!s.fromAdditions) return;
      var seen = {};
      s.bands.forEach(function (b) {
        if (!b) return;
        var g = groupOf(b);
        if (seen[g]) return;
        seen[g] = 1;
        if (!bandIndex[g]) bandIndex[g] = [];
        // avoid duplicates if mergeAdditions called twice
        var already = bandIndex[g].some(function (x) { return x.id === s.id; });
        if (!already) bandIndex[g].push(s);
      });
    });
    Object.keys(bandIndex).forEach(function (k) {
      bandIndex[k].sort(function (a, b) {
        var ad = a.date || "9999", bd = b.date || "9999";
        return ad < bd ? -1 : ad > bd ? 1 : a.id - b.id;
      });
    });

    // rebuild venueIndex entries for new shows
    SHOWS.forEach(function (s) {
      if (!s.fromAdditions || !s.venue) return;
      if (!venueIndex[s.venue]) venueIndex[s.venue] = [];
      var already = venueIndex[s.venue].some(function (x) { return x.id === s.id; });
      if (!already) venueIndex[s.venue].push(s);
    });
  }

  function mergeAdditions(rawArray) {
    if (!rawArray || !rawArray.length) return;
    rawArray.forEach(function (raw) {
      // deduplicate by headliner+date
      var dup = SHOWS.some(function (s) {
        return s.headliner === (raw.headliner || "") && s.date === (raw.date || null);
      });
      if (dup) return;
      var enriched = enrichShow(raw, SHOWS.length);
      SHOWS.push(enriched);
    });
    recomputeDerived();
    // re-render whichever view is currently showing
    setView(CURRENT_VIEW);
  }

  function fetchAdditions() {
    var url = "concerts-additions.json?_=" + Date.now();
    var xhr = new XMLHttpRequest();
    xhr.open("GET", url, true);
    xhr.onreadystatechange = function () {
      if (xhr.readyState !== 4) return;
      if (xhr.status === 200 || xhr.status === 0) {
        try {
          var data = JSON.parse(xhr.responseText);
          // also merge any locally-pending shows not yet deployed
          var pending = [];
          try { pending = JSON.parse(localStorage.getItem("concert_pending") || "[]"); } catch (e) {}
          // combine: committed additions + pending (dedup handles overlap)
          mergeAdditions(data.concat(pending));
        } catch (e) { /* malformed JSON — skip */ }
      }
    };
    xhr.send();
  }

  // --------------------------------------------------------------- boot
  function boot() {
    buildThemePicker();
    if (!RAW.length) {
      app.innerHTML = '<div class="empty">No data found. Double-click <b>Refresh &amp; Open.bat</b> to ' +
                      'generate <code>data.js</code> from your spreadsheet.</div>';
      return;
    }
    el("masthead-serial").innerHTML = "No.&nbsp;" + String(SHOWS.length).padStart(6, "0");
    var metaTxt = (META.showCount != null ? META.showCount + " shows" : SHOWS.length + " shows");
    if (META.generatedAt) metaTxt += " &middot; updated " + esc(META.generatedAt);
    el("masthead-meta").innerHTML = metaTxt;
    var srcFile = (META.source || 'Concerts.xlsm').replace(/.*[\\/]/, '');
    el("footer-meta").innerHTML = "Source: " + esc(srcFile);

    Array.prototype.forEach.call(document.querySelectorAll(".tab"), function (t) {
      t.addEventListener("click", function () { setView(t.getAttribute("data-view")); });
    });

    // hamburger menu (mobile)
    var navToggle = el("nav-toggle");
    var mobileNav = el("mobile-nav");
    if (navToggle && mobileNav) {
      function positionMobileNav() {
        var hdr = document.querySelector(".masthead");
        if (hdr) mobileNav.style.top = hdr.offsetHeight + "px";
      }
      positionMobileNav();
      window.addEventListener("resize", positionMobileNav);

      navToggle.addEventListener("click", function (e) {
        e.stopPropagation();
        var open = mobileNav.classList.toggle("is-open");
        navToggle.innerHTML = open ? "&#10005;" : "&#9776;";
      });

      document.addEventListener("click", function (e) {
        if (!mobileNav.contains(e.target) && !navToggle.contains(e.target)) {
          mobileNav.classList.remove("is-open");
          navToggle.innerHTML = "&#9776;";
        }
      });
    }

    Array.prototype.forEach.call(document.querySelectorAll(".mobile-nav-item"), function (t) {
      t.addEventListener("click", function () { setView(t.getAttribute("data-view")); });
    });

    // Delegated: clicking a band or venue name inside any ticket jumps to its page.
    app.addEventListener("click", function (e) {
      if (!e.target.closest) return;
      var band = e.target.closest(".band-link");
      if (band) {
        e.preventDefault();
        showDetail("artist", band.getAttribute("data-artist"));
        return;
      }
      var venue = e.target.closest(".venue-link");
      if (venue) {
        e.preventDefault();
        showDetail("venue", venue.getAttribute("data-venue"));
      }
    });

    var fab = el("add-show-fab");
    if (fab) fab.addEventListener("click", openAddModal);

    var closeBtn = el("add-modal-close");
    if (closeBtn) closeBtn.addEventListener("click", closeAddModal);

    var overlay = el("add-modal-overlay");
    if (overlay) overlay.addEventListener("click", function (e) {
      if (e.target === overlay) closeAddModal();
    });

    document.addEventListener("keydown", function (e) {
      if (e.key === "Escape") closeAddModal();
    });

    setView("overview");
    fetchAdditions();
  }
  boot();
})();
