// Tour names sourced from setlist.fm. Key: "headliner|date|venueRaw" (matches cache key format).
window.TOUR_DATA = {
  'AC/DC|2008-11-03|Bankers Life Fieldhouse (Conseco)': 'Black Ice',
  'Aerosmith|1997-08-31|Ruoff Home Mortgage Music Center (Deer Creek/Verizon Wireless/Klipsch)': 'Nine Lives',
  'Aerosmith|1998-09-21|Ruoff Home Mortgage Music Center (Deer Creek/Verizon Wireless/Klipsch)': 'Nine Lives',
  'Aerosmith|2001-07-09|Ruoff Home Mortgage Music Center (Deer Creek/Verizon Wireless/Klipsch)': 'Just Push Play',
  'Aerosmith|2002-09-22|Ruoff Home Mortgage Music Center (Deer Creek/Verizon Wireless/Klipsch)': 'Girls of Summer',
  'Aerosmith|2003-08-17|Ruoff Home Mortgage Music Center (Deer Creek/Verizon Wireless/Klipsch)': 'Rocksimus Maximus',
  'Aerosmith|2004-06-08|Ruoff Home Mortgage Music Center (Deer Creek/Verizon Wireless/Klipsch)': 'Honkin\' On Bobo',
  'Aerosmith|2006-10-13|Ruoff Home Mortgage Music Center (Deer Creek/Verizon Wireless/Klipsch)': 'Route of All Evil',
  'Aerosmith|2010-09-02|Riverbend Music Center': 'Cocked, Locked, Ready to Rock',
  'Alanis Morisette|2021-09-10|Ruoff Home Mortgage Music Center (Deer Creek/Verizon Wireless/Klipsch)': 'Jagged Little Pill 25th Anniversary Tour',
  'Barenaked Ladies|2001-07-18|Ruoff Home Mortgage Music Center (Deer Creek/Verizon Wireless/Klipsch)': 'Under Where? Summer Tour',
  'Beck|2016-09-22|IU Auditorium': 'WOW',
  'Beck|2019-08-04|Ruoff Home Mortgage Music Center (Deer Creek/Verizon Wireless/Klipsch)': 'The Night Running Tour',
  'Ben Harper|2003-06-28|Ruoff Home Mortgage Music Center (Deer Creek/Verizon Wireless/Klipsch)': 'Diamonds on the Inside',
  'Better Than Ezra|2010-12-05|The Vogue': 'Road to Mardi Gras 2010 Tour',
  'Better Than Ezra|2024-05-13|The Vogue': 'Live a Little',
  'Big Head Todd & The Monsters|2010-08-19|The Vogue': 'Rocksteady Tour 2010',
  'Big Head Todd & The Monsters|2019-11-01|The Vogue': 'Winter Tour 2019-2020',
  'Big Head Todd & The Monsters|2024-01-18|The Palladium': 'Winter Tour 2024',
  'Big Head Todd & The Monsters|2025-01-16|Brown County Music Center': '40th Anniversary Tour',
  'Black Sabbath|2016-09-02|Ruoff Home Mortgage Music Center (Deer Creek/Verizon Wireless/Klipsch)': 'The End',
  'Bon Jovi|2003-07-30|Ruoff Home Mortgage Music Center (Deer Creek/Verizon Wireless/Klipsch)': 'Bounce',
  'Bush|1996-04-20|Assembly Hall': 'Sixteen Stone',
  'Chickenfoot|2009-08-07|Chicago Theater': '2009 North American Tour',
  'Coldplay|2003-03-04|Old National Centre (The Murat)': 'A Rush of Blood to the Head',
  'Coldplay|2005-08-12|Ruoff Home Mortgage Music Center (Deer Creek/Verizon Wireless/Klipsch)': 'Twisted Logic',
  'Colin Hay|2012-03-11|The Vogue': 'Gathering Mercury Tour',
  'Counting Crows|2002-10-16|Elliott Hall (Purdue)': 'Hard Candy',
  'Counting Crows|2003-04-17|Clowes Hall (Butler)': 'Hard Candy',
  'Counting Crows|2007-08-04|Ruoff Home Mortgage Music Center (Deer Creek/Verizon Wireless/Klipsch)': '2007 Tour',
  'Counting Crows|2008-08-28|Ruoff Home Mortgage Music Center (Deer Creek/Verizon Wireless/Klipsch)': 'Saturday Nights & Sunday Mornings',
  'Counting Crows|2012-07-01|Lawn at White River': 'The Outlaw Roadshow',
  'Counting Crows|2018-09-06|Ruoff Home Mortgage Music Center (Deer Creek/Verizon Wireless/Klipsch)': '25 Years and Counting',
  'Counting Crows|2023-06-17|Lawn at White River': 'Banshee Season',
  'Counting Crows|2025-06-14|Lawn at White River': 'The Complete Sweets! Tour',
  'Crosby, Stills, Nash & Young|2002-02-20|Bankers Life Fieldhouse (Conseco)': 'Tour Of America',
  'Jimmy Buffett & The Coral Reefer Band|1997-06-25|Ruoff Home Mortgage Music Center (Deer Creek/Verizon Wireless/Klipsch)': 'Havañ a Daydreamin\'',
  'Jimmy Buffett & The Coral Reefer Band|2000-07-20|Ruoff Home Mortgage Music Center (Deer Creek/Verizon Wireless/Klipsch)': 'Tuesdays, Thursdays, Saturdays',
  'Jimmy Buffett & The Coral Reefer Band|2000-08-19|Riverbend Music Center':                                                   'Tuesdays, Thursdays, Saturdays',
  'Jimmy Buffett & The Coral Reefer Band|2001-09-25|Ruoff Home Mortgage Music Center (Deer Creek/Verizon Wireless/Klipsch)': '2001: A Beach Odyssey',
  'Jimmy Buffett & The Coral Reefer Band|2002-06-22|Tinley Park':                                                             'Far Side of the World',
  'Jimmy Buffett & The Coral Reefer Band|2003-06-26|Ruoff Home Mortgage Music Center (Deer Creek/Verizon Wireless/Klipsch)': 'Tiki Time',
  'Jimmy Buffett & The Coral Reefer Band|2004-07-08|Ruoff Home Mortgage Music Center (Deer Creek/Verizon Wireless/Klipsch)': 'License to Chill',
  'Jimmy Buffett & The Coral Reefer Band|2009-08-11|Ruoff Home Mortgage Music Center (Deer Creek/Verizon Wireless/Klipsch)': 'SummerZCool',
  'Jimmy Buffett & The Coral Reefer Band|2011-08-25|Ruoff Home Mortgage Music Center (Deer Creek/Verizon Wireless/Klipsch)': 'Welcome to Fin Land',
  'Jimmy Buffett & The Coral Reefer Band|2013-06-27|Ruoff Home Mortgage Music Center (Deer Creek/Verizon Wireless/Klipsch)': 'Songs From St. Somewhere',
  'Jimmy Buffett & The Coral Reefer Band|2014-06-26|Ruoff Home Mortgage Music Center (Deer Creek/Verizon Wireless/Klipsch)': 'This One\'s for You',
  'Jimmy Buffett & The Coral Reefer Band|2016-06-23|Ruoff Home Mortgage Music Center (Deer Creek/Verizon Wireless/Klipsch)': 'I Don\'t Know',
  'Jimmy Buffett & The Coral Reefer Band|2018-05-24|Ruoff Home Mortgage Music Center (Deer Creek/Verizon Wireless/Klipsch)': 'Son of a Son of a Sailor',
  'Jimmy Buffett & The Coral Reefer Band|2021-07-10|Ruoff Home Mortgage Music Center (Deer Creek/Verizon Wireless/Klipsch)': 'Life on the Flip Side',
  'Dave Matthews Band|1999-06-24|Ruoff Home Mortgage Music Center (Deer Creek/Verizon Wireless/Klipsch)': 'Summer 1999',
  'Dave Matthews Band|2000-06-22|Ruoff Home Mortgage Music Center (Deer Creek/Verizon Wireless/Klipsch)': 'Summer 2000',
  'Dave Matthews Band|2000-06-23|Ruoff Home Mortgage Music Center (Deer Creek/Verizon Wireless/Klipsch)': 'Summer 2000',
  'Dave Matthews Band|2000-06-24|Ruoff Home Mortgage Music Center (Deer Creek/Verizon Wireless/Klipsch)': 'Summer 2000',
  'Dave Matthews Band|2002-08-10|Ruoff Home Mortgage Music Center (Deer Creek/Verizon Wireless/Klipsch)': 'Summer 2002',
  'Dave Matthews Band|2002-08-11|Ruoff Home Mortgage Music Center (Deer Creek/Verizon Wireless/Klipsch)': 'Summer 2002',
  'Dave Matthews Band|2004-06-20|Ruoff Home Mortgage Music Center (Deer Creek/Verizon Wireless/Klipsch)': 'Summer 2004',
  'Dave Matthews Band|2006-06-03|Ruoff Home Mortgage Music Center (Deer Creek/Verizon Wireless/Klipsch)': 'Summer 2006',
  'Dave Matthews Band|2007-08-18|Ruoff Home Mortgage Music Center (Deer Creek/Verizon Wireless/Klipsch)': 'Summer 2007',
  'Dave Matthews Band|2010-06-19|Ruoff Home Mortgage Music Center (Deer Creek/Verizon Wireless/Klipsch)': '2010 Summer Tour',
  'Dave Matthews Band|2014-06-21|Ruoff Home Mortgage Music Center (Deer Creek/Verizon Wireless/Klipsch)': 'Summer 2014',
  'Dave Matthews Band|2023-07-01|Ruoff Home Mortgage Music Center (Deer Creek/Verizon Wireless/Klipsch)': '2023 Summer Tour',
  'Dave Matthews Band|2024-06-29|Ruoff Home Mortgage Music Center (Deer Creek/Verizon Wireless/Klipsch)': 'Summer Tour 2024',
  'Dave Matthews Band|2025-07-11|Ruoff Home Mortgage Music Center (Deer Creek/Verizon Wireless/Klipsch)': 'Summer Tour 2025',
  'Dave Matthews Band|2025-07-12|Ruoff Home Mortgage Music Center (Deer Creek/Verizon Wireless/Klipsch)': 'Summer Tour 2025',
  'David Byrne|2026-05-01|Old National Centre': 'Who Is the Sky?',
  'David Lee Roth|2002-06-01|Tinley Park': 'Song for Song, the Heavyweight Champs of Rock and Roll',
  'Dead & Company|2022-06-28|Ruoff Home Mortgage Music Center (Deer Creek/Verizon Wireless/Klipsch)': 'Summer Tour 22',
  'Death Cab For Cutie|2023-05-31|Lawn at White River': 'Asphalt Meadows Tour',
  'Def Leppard|2003-03-22|Bankers Life Fieldhouse (Conseco)': 'X',
  'Def Leppard|2006-07-22|Ruoff Home Mortgage Music Center (Deer Creek/Verizon Wireless/Klipsch)': 'Yeah! Tour',
  'Def Leppard|2007-07-06|Ruoff Home Mortgage Music Center (Deer Creek/Verizon Wireless/Klipsch)': 'Downstage Thrust Tour',
  'Def Leppard|2009-07-23|Ruoff Home Mortgage Music Center (Deer Creek/Verizon Wireless/Klipsch)': 'Songs from the Sparkle Lounge Tour',
  'Def Leppard|2011-08-12|Ruoff Home Mortgage Music Center (Deer Creek/Verizon Wireless/Klipsch)': 'Mirror Ball',
  'Def Leppard|2012-08-24|Ruoff Home Mortgage Music Center (Deer Creek/Verizon Wireless/Klipsch)': 'Rock of Ages Tour 2012',
  'Def Leppard|2016-07-01|Ruoff Home Mortgage Music Center (Deer Creek/Verizon Wireless/Klipsch)': '2016 North American Tour',
  'Def Leppard|2017-06-25|Ruoff Home Mortgage Music Center (Deer Creek/Verizon Wireless/Klipsch)': '2017 North American Tour',
  'Def Leppard|2018-07-03|Ruoff Home Mortgage Music Center (Deer Creek/Verizon Wireless/Klipsch)': 'North American Tour 2018',
  'Doobie Brothers|2022-07-14|Ruoff Home Mortgage Music Center (Deer Creek/Verizon Wireless/Klipsch)': '50th Anniversary Tour',
  'Eric Clapton|2001-06-02|Bankers Life Fieldhouse (Conseco)': 'Reptile',
  'Extreme|2024-02-07|Old National Centre': 'Thicker Than Blood Tour 2024',
  'Fun.|2013-07-20|Merriweather Post Pavillion': 'Most Nights Summer Tour',
  'Gin Blossoms|2019-02-24|The Vogue': 'New Miserable Experience',
  'Green Day|2005-09-12|Bankers Life Fieldhouse (Conseco)': 'American Idiot',
  'Guns \'N\' Roses|2002-11-18|Allstate Arena': 'Chinese Democracy Tour 01/02',
  'Guns \'N\' Roses|2021-09-08|Lucas Oil Stadium': 'We\'re F\'N Back! Tour 2021',
  'Hootie & The Blowfish|2019-08-17|Ruoff Home Mortgage Music Center (Deer Creek/Verizon Wireless/Klipsch)': 'Group Therapy Tour',
  'Hootie & The Blowfish|2024-06-08|Ruoff Home Mortgage Music Center (Deer Creek/Verizon Wireless/Klipsch)': 'Summer Camp with Trucks Tour',
  'Iron Maiden|2012-07-19|Ruoff Home Mortgage Music Center (Deer Creek/Verizon Wireless/Klipsch)': 'Maiden England',
  'Jimmy Eat World|2002-08-02|Old National Centre (The Murat Egyptian Room)': 'Bleed American',
  'Jimmy Page/Robert Plant|1998-06-09|Market Square Arena': 'Walking Into Everywhere Tour 1998',
  'Journey|2001-07-17|Ruoff Home Mortgage Music Center (Deer Creek/Verizon Wireless/Klipsch)': 'The Arrival',
  'Journey|2005-07-09|Ruoff Home Mortgage Music Center (Deer Creek/Verizon Wireless/Klipsch)': '30th Anniversary Tour',
  'Journey|2013-02-10|Ft. Wayne Coliseum': 'Eclipse',
  'Journey|2014-06-28|Ruoff Home Mortgage Music Center (Deer Creek/Verizon Wireless/Klipsch)': '2014 Summer Tour',
  'Journey|2017-07-23|Ruoff Home Mortgage Music Center (Deer Creek/Verizon Wireless/Klipsch)': 'North American Tour 2017',
  'Journey|2026-03-17|Bankers Life Fieldhouse (Conseco)': 'Final Frontier Tour',
  'Kings of Leon|2010-09-03|Ruoff Home Mortgage Music Center (Deer Creek/Verizon Wireless/Klipsch)': '2010 Summer Tour',
  'Kiss|2012-09-01|Ruoff Home Mortgage Music Center (Deer Creek/Verizon Wireless/Klipsch)': 'The Tour',
  'Lake Street Dive|2024-07-12|Lawn at White River': 'Good Together',
  'Live|1995-09-01|Ruoff Home Mortgage Music Center (Deer Creek/Verizon Wireless/Klipsch)': 'Throwing Copper',
  'Lynard Skynard|2001-06-29|Ruoff Home Mortgage Music Center (Deer Creek/Verizon Wireless/Klipsch)': 'Edge of Forever',
  'Lynard Skynard|2004-09-24|Ruoff Home Mortgage Music Center (Deer Creek/Verizon Wireless/Klipsch)': 'Vicious Cycle',
  'MatchBox 20|2001-03-06|Bankers Life Fieldhouse (Conseco)': 'Mad Season',
  'MatchBox 20|2001-08-07|Ruoff Home Mortgage Music Center (Deer Creek/Verizon Wireless/Klipsch)': 'Mad Season',
  'Meghan Trainor|2024-10-04|Ruoff Home Mortgage Music Center (Deer Creek/Verizon Wireless/Klipsch)': 'The Timeless Tour',
  'Motley Crue|2005-03-08|Schotenstein Center': 'Red, White & Crüe Tour 2005...Better Live Than Dead',
  'Motley Crue|2005-09-21|Bankers Life Fieldhouse (Conseco)': 'Carnival of Sins',
  'Motley Crue|2006-02-21|Ft. Wayne Coliseum': 'Carnival of Sins',
  'Motley Crue|2008-07-08|Ruoff Home Mortgage Music Center (Deer Creek/Verizon Wireless/Klipsch)': 'Crüe Fest',
  'Motley Crue|2011-07-02|Ruoff Home Mortgage Music Center (Deer Creek/Verizon Wireless/Klipsch)': 'Summer Tour',
  'Motley Crue|2014-07-05|Ruoff Home Mortgage Music Center (Deer Creek/Verizon Wireless/Klipsch)': 'The Final Tour',
  'Motley Crue|2015-08-20|Bankers Life Fieldhouse (Conseco)': 'The Final Tour',
  'Motley Crue|2022-08-16|Lucas Oil Stadium': 'The Stadium Tour',
  'Nathaniel Rateliff & The Night Sweats|2025-03-18|Fishers Event Center': 'South of Here Tour',
  'New Kids On The Block|2024-08-25|Ruoff Home Mortgage Music Center (Deer Creek/Verizon Wireless/Klipsch)': 'Magic Summer Tour 2024',
  'Oasis|2006-03-23|Old National Centre (The Murat)': 'Don\'t Believe the Truth',
  'Oasis|2025-08-28|Soldier Field': 'Oasis Live \'25',
  'Ozzy Osbourne|2002-08-13|Ruoff Home Mortgage Music Center (Deer Creek/Verizon Wireless/Klipsch)': 'Down to Earth',
  'P!nk|2024-10-12|Lucas Oil Stadium': 'Summer Carnival',
  'Paul McCartney|2002-10-05|Bankers Life Fieldhouse (Conseco)': 'Back in the U.S.',
  'Paul McCartney|2013-07-14|Bankers Life Fieldhouse (Conseco)': 'Out There!',
  'Pearl Jam|2003-06-22|Ruoff Home Mortgage Music Center (Deer Creek/Verizon Wireless/Klipsch)': 'Riot Act',
  'Pete Yorn|2014-10-07|Deluxe @ The Old National Centre (The Murat)': 'You & Me Acoustic Tour 2014',
  'Pete Yorn|2025-09-19|The Vogue': 'You & Me Solo Acoustic Tour 2025',
  'Peter Gabriel|2003-07-02|Ruoff Home Mortgage Music Center (Deer Creek/Verizon Wireless/Klipsch)': 'Growing Up',
  'Phish|2009-06-19|Ruoff Home Mortgage Music Center (Deer Creek/Verizon Wireless/Klipsch)': 'Summer Tour 2009',
  'Poison|1999-06-08|Ruoff Home Mortgage Music Center (Deer Creek/Verizon Wireless/Klipsch)': 'Summer Jam \'99',
  'Poison|2001-07-25|Ruoff Home Mortgage Music Center (Deer Creek/Verizon Wireless/Klipsch)': 'Glam Slam Metal Jam',
  'Poison|2003-06-08|Ruoff Home Mortgage Music Center (Deer Creek/Verizon Wireless/Klipsch)': 'Harder, Louder, Faster',
  'Poison|2007-08-21|Ruoff Home Mortgage Music Center (Deer Creek/Verizon Wireless/Klipsch)': 'POISON\'D Summer Tour 2007',
  'Poison|2008-08-15|Ruoff Home Mortgage Music Center (Deer Creek/Verizon Wireless/Klipsch)': 'Live, Raw, & Uncut',
  'Poison|2018-06-07|Ruoff Home Mortgage Music Center (Deer Creek/Verizon Wireless/Klipsch)': 'Nothin\' but a Good Time Tour 2018',
  'Prince|2004-04-12|Bankers Life Fieldhouse (Conseco)': 'Musicology Live 2004ever',
  'Queen + Adam Lambert|2014-06-19|United Center': 'A Once in a Lifetime Experience',
  'Queen Extravaganza|2012-06-01|House of Blues (CHI)': '2012 Queen Extravaganza North American Summer Tour',
  'Red Hot Chili Peppers|2000-07-07|Ruoff Home Mortgage Music Center (Deer Creek/Verizon Wireless/Klipsch)': 'Californication',
  'REM|2004-10-20|Old National Centre (The Murat)': 'Around the Sun',
  'Rob Zombie|2006-04-09|Old National Centre (The Murat Egyptian Room)': 'Educated Horses',
  'Robert Plant & Alison Krauss|2022-06-09|Lawn at White River': 'Raising The Roof Tour',
  'Rolling Stones|2002-09-13|Comiskey Park': 'Licks World Tour',
  'Rolling Stones|2002-10-20|Nationwide Arena': 'Licks World Tour',
  'Rolling Stones|2005-09-15|Nationwide Arena': 'A Bigger Bang',
  'Rolling Stones|2015-07-04|Indianapolis Motor Speedway': 'Zip Code',
  'Rolling Stones|2024-06-15|Cleveland Browns Stadium': 'Hackney Diamonds',
  'Rush|2004-06-04|Ruoff Home Mortgage Music Center (Deer Creek/Verizon Wireless/Klipsch)': 'R30: 30th Anniversary Tour',
  'Sammy Hagar & The Circle|2019-05-23|Lawn at White River': 'Space Between Tour 2019',
  'Sammy Hagar & The Circle|2022-06-15|Ruoff Home Mortgage Music Center (Deer Creek/Verizon Wireless/Klipsch)': 'Crazy Times!',
  'Sammy Hagar & The Waboritas|1999-09-09|Old National Centre (The Murat)': 'Red Voodoo',
  'Sammy Hagar & The Waboritas|2005-05-13|Rosemont Theater': 'Cinco de Cabo',
  'Sammy Hagar & The Waboritas|2006-07-14|Ruoff Home Mortgage Music Center (Deer Creek/Verizon Wireless/Klipsch)': 'Livin\' It Up!',
  'Sammy Hagar & The Waboritas|2007-10-28|Old National Centre (The Murat)': '24/365 Tour',
  'Sammy Hagar & The Waboritas|2007-11-10|Chicago Theater': '24/365 Tour',
  'Sammy Hagar|1997-07-16|Old National Centre (The Murat)': 'Marching to Mars',
  'Sammy Hagar|1999-06-18|Ft. Wayne Coliseum': 'Red Voodoo',
  'Sammy Hagar|1999-09-09|Old National Centre (The Murat)': 'Red Voodoo',
  'Sammy Hagar|2002-06-02|Ruoff Home Mortgage Music Center (Deer Creek/Verizon Wireless/Klipsch)': 'Song for Song, the Heavyweight Champs of Rock and Roll',
  'Sammy Hagar|2007-11-10|Chicago Theater': '24/365 Tour',
  'Sammy Hagar|2019-05-23|Lawn at White River': 'Space Between Tour 2019',
  'Sammy Hagar|2022-06-15|Ruoff Home Mortgage Music Center (Deer Creek/Verizon Wireless/Klipsch)': 'Crazy Times!',
  'Sammy Hagar|2024-08-30|Ruoff Home Mortgage Music Center (Deer Creek/Verizon Wireless/Klipsch)': 'The Best of All Worlds Tour',
  'Sammy Hagar|2026-06-14|Ruoff Home Mortgage Music Center (Deer Creek/Verizon Wireless/Klipsch)': 'The Best of All Worlds Tour',
  'Sara McLachlan|2004-08-27|Bankers Life Fieldhouse (Conseco)': 'Afterglow Live',
  'Simon & Garfunkel|2004-06-23|Bankers Life Fieldhouse (Conseco)': 'Old Friends',
  'Smashing Pumpkins|1997-01-18|Assembly Hall': 'Infinite Sadness',
  'Soundgarden|2011-07-16|UIC Pavillion': '2011 Summer Tour',
  'Stone Temple Pilots|2008-05-23|Indianapolis Motor Speedway': '2008 Reunion Tour',
  'Stone Temple Pilots|2024-09-15|Ruoff Home Mortgage Music Center (Deer Creek/Verizon Wireless/Klipsch)': 'The Jubilee Tour 2024',
  'Tesla|2001-03-26|The Vogue': 'RePlugged Reunion Tour',
  'Tesla|2004-04-20|Old National Centre (The Murat Egyptian Room)': 'Into the Now',
  'Tesla|2007-07-17|The Vogue': 'Real to Reel',
  'The Black Crowes|1998-09-02|Mars': 'Sho Nuff',
  'The Black Crowes|2001-06-01|Ruoff Home Mortgage Music Center (Deer Creek/Verizon Wireless/Klipsch)': 'The Tour of Brotherly Love',
  'The Black Crowes|2006-08-05|Lawn at White River': '2006 Summer Tour',
  'The Black Crowes|2010-08-25|Old National Centre (The Murat)': 'Say Goodnight to the Bad Guys',
  'The Black Crowes|2021-08-01|Ruoff Home Mortgage Music Center (Deer Creek/Verizon Wireless/Klipsch)': 'The Black Crowes Present: Shake Your Money Maker',
  'The Black Crowes|2026-07-17|Ruoff Home Mortgage Music Center (Deer Creek/Verizon Wireless/Klipsch)': 'Southern Hospitality Tour',
  'The Cure|2023-06-25|Merriweather Post Pavillion': 'Shows of a Lost World',
  'The Eagles|1995-04-27|Ruoff Home Mortgage Music Center (Deer Creek/Verizon Wireless/Klipsch)': 'Hell Freezes Over',
  'The Eagles|2018-03-12|Bankers Life Fieldhouse (Conseco)': 'North American Tour 2018',
  'The Lemonheads|2024-09-19|The Vogue': 'It\'s A Shame About Come On Feel Tour',
  'The Struts|2024-08-16|Holiday Park (Rock the Ruins)': 'Pretty Vicious Tour 2024',
  'The Who|2002-08-25|Ruoff Home Mortgage Music Center (Deer Creek/Verizon Wireless/Klipsch)': 'The Who Tour 2002',
  'Them Crooked Vultures|2010-05-18|Old National Centre (The Murat)': 'Deserve the Future',
  'Toad the Wet Sprocket|2003-02-23|The Vogue': 'PS Tour 2003',
  'Tom Petty & The Heartbreakers|2002-08-14|Ruoff Home Mortgage Music Center (Deer Creek/Verizon Wireless/Klipsch)': 'Summer Tour 2002',
  'Tom Petty & The Heartbreakers|2010-07-10|Ruoff Home Mortgage Music Center (Deer Creek/Verizon Wireless/Klipsch)': 'Mojo Tour 2010',
  'Tom Petty & The Heartbreakers|2013-06-28|Marcus Amphitheater': '2013 Tour',
  'Tom Petty & The Heartbreakers|2017-05-29|Red Rocks Amphitheatre': '40th Anniversary Tour',
  'Tom Petty & The Heartbreakers|2017-05-30|Red Rocks Amphitheatre': '40th Anniversary Tour',
  'U2|2001-05-10|Bankers Life Fieldhouse (Conseco)': 'Elevation',
  'Van Halen|1998-07-22|Ruoff Home Mortgage Music Center (Deer Creek/Verizon Wireless/Klipsch)': 'III Tour',
  'Van Halen|2004-07-01|Ruoff Home Mortgage Music Center (Deer Creek/Verizon Wireless/Klipsch)': 'Best of Both Worlds',
  'Van Halen|2004-07-19|United Center': 'Best of Both Worlds',
  'Van Halen|2004-11-11|Ft. Wayne Coliseum': 'Best of Both Worlds',
  'Van Halen|2007-10-14|Bankers Life Fieldhouse (Conseco)': 'North American Tour 2007-2008',
  'Van Halen|2012-02-22|Bankers Life Fieldhouse (Conseco)': 'A Different Kind of Truth',
  'Van Halen|2012-02-24|United Center': 'A Different Kind of Truth',
  'Van Halen|2015-09-02|Ruoff Home Mortgage Music Center (Deer Creek/Verizon Wireless/Klipsch)': 'North American Tour 2015',
  'Weezer|2002-07-17|Ruoff Home Mortgage Music Center (Deer Creek/Verizon Wireless/Klipsch)': 'Enlightenment Tour',
  'Weezer|2018-07-08|Ruoff Home Mortgage Music Center (Deer Creek/Verizon Wireless/Klipsch)': 'North American Summer Tour 2018',
  'Weezer|2019-03-16|Royal Farms Arena': 'North American Spring Tour 2019',
  'Weird Al Yankovic|2007-06-30|Star Plaza': 'Straight Outta Lynwood',
  'Weird Al Yankovic|2018-03-29|The Palladium': 'The Ridiculously Self-Indulgent Ill-Advised Vanity Tour',
  'Weird Al Yankovic|2019-08-29|Lawn at White River': 'Strings Attached',
  'Weird Al Yankovic|2023-02-03|Brown County Music Center': 'The Unfortunate Return of The Ridiculously Self-Indulgent Ill-Advised Vanity Tour',
  'Wilco|2011-09-13|Old National Centre (The Murat)': 'The Whole Love',
};